import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Best Show</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper">
        <header>header</header>
        <main className='main'>
          <div className="container">
            <p>main</p>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
